#! /bin/sh

#Autostart application
pgrep -x sxhkd > /dev/null || sxhkd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xidlehook --not-when-audio --not-when-fullscreen --timer 1800 'systemctl suspend-then-hibernate' '' &
~/.config/polybar/launch.sh &
#pcmanfm -d &
dunst &
#picom &
feh --bg-fill /home/aniket/Pictures/backgrounds/1.jpg &
#nitrogen --restore &

#bspwm settings
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 &

bspc config normal_border_color "#0A4D68"
bspc config active_border_color "#00FFCA"
bspc config focused_border_color "#05BFDB"
bspc config presel_feedback_color "#088395"

bspc config border_width         2
bspc config window_gap           7
bspc config border-radius        20.0

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# enable mouse for floating windows
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# rules for application
#bspc rule -a '*' state=floating

