#! /bin/sh

#Autostart application
pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh &
nitrogen --restore &
#feh --bg-scale 4k-Cityscape-Desktop-Wallpaper.png &
nm-applet &
blueman-applet &
dunst &
picom &
#exec /usr/bin/trayer --edge top --align right --expand true --width 8 --height 22 --transparent true --tint 0x212A3E --alpha 0 &

#bspwm settings
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 &

bspc config border_width         2
bspc config window_gap           9

bspc config normal_border_color "#0A4D68"
bspc config active_border_color "#00FFCA"
bspc config focused_border_color "#05BFDB"
bspc config presel_feedback_color "#088395"

bspc config focus_follows_pointer false
bspc config pointer_follows_focus true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

